
name: publish
on: [push]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t justinvoss.com .
      - name: jekyll build
        run: docker run -v "$PWD:/jekyll/" -t justinvoss.com jekyll build
      - name: ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          name: id_ed25519
      - name: rsync
        run: rsync -v --compress --recursive --checksum --delete _site/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
